### ISSUE TITLE
希望getter.ts文件支持export const getters = {}格式

### ISSUE THREAD

**Issue by fulus06** [normojs/vite-plugin-store#4]
> 当你使用GitHub时，请使用中英双语提问，格式为：英文 | 中文，如：hot update support | 支持热加载
>
> 或者在gitee上提问：https://gitee.com/source-code-online/vite-plugin-store/issues

##### 如何引起的当前问题，简单描述 | What caused the problem?
在getter.ts 文件中输入
```js

export const getters = {
  getUserRoleInfo(state) {
    return `${state.path}-user role getters-${Math.random()}`
  },
}

```

##### 错误信息 | Report an error message
![image](https://user-images.githubusercontent.com/12890684/128668087-5f6a1b5c-4b5e-445e-98c3-f884b78a3c6b.png)

**Comment by normojs** [comment]
支持三种方式 | Three modes are supported

demo: `examples\spa\src\store\user\role\getters.ts`

```js
// 1
export default {
  getUserRoleInfo: (state) => {
    return `${state.path}-user role getters-${Math.random()}`
  },
}

// 2
/* export const getUserRoleInfo = (state) => {
  return `${state.path}-user role getters-${Math.random()}`
} */

// 3
/* export const getters = {
  getAccountInfo(state) {
    return `${state.path}-user role getters-${Math.random()}`
  },
} */

```
